### ISSUE TITLE
flashcache compile error on linux 3.6.0

### ISSUE THREAD

**Issue by ghost** [facebookarchive/flashcache#86]
Hello.

Flashcache fails to compile on linux-3.6.0. Any hints?

hn flashcache # make KERNEL_TREE=/usr/src/linux-3.6.0/
make -C src KERNEL_TREE=/usr/src/linux-3.6.0/ PWD=/usr/src/flashcache/src all
make[1]: Entering directory `/usr/src/flashcache/src'
make -C /usr/src/linux-3.6.0/ M=/usr/src/flashcache/src modules V=0
make[2]: Entering directory`/usr/src/linux-3.6.0'
  CC [M]  /usr/src/flashcache/src/flashcache_conf.o
/usr/src/flashcache/src/flashcache_conf.c: In function 'flashcache_ctr':
/usr/src/flashcache/src/flashcache_conf.c:1092:4: error: 'struct dm_target' has no member named 'split_io'
/usr/src/flashcache/src/flashcache_conf.c: At top level:
/usr/src/flashcache/src/flashcache_conf.c:1534:2: warning: initialization from incompatible pointer type
make[3]: **\* [/usr/src/flashcache/src/flashcache_conf.o] Error 1
make[2]: **\* [_module_/usr/src/flashcache/src] Error 2
make[2]: Leaving directory `/usr/src/linux-3.6.0'
make[1]: *** [modules] Error 2
make[1]: Leaving directory`/usr/src/flashcache/src'
make: **\* [all] Error 2
hn flashcache #

cheers
t.
