### ISSUE TITLE
Linux 4.4 build failure.

### ISSUE THREAD

**Issue by vinsonlee** [facebookarchive/flashcache#215]
flashcache does not build with Linux 4.4.

  CC [M]  flashcache/src/flashcache_conf.o
flashcache/src/flashcache_conf.c:1718:2: error: unknown field ‘ioctl’ specified in initializer
  .ioctl  = flashcache_ioctl,
  ^

The build failure is introduced with Linux 4.4-rc1 commit e56f81e0b01ef4e45292d8c1e19edd4d09724e14 "dm: refactor ioctl handling".

commit e56f81e0b01ef4e45292d8c1e19edd4d09724e14
Author: Christoph Hellwig hch@lst.de
Date:   Thu Oct 15 14:10:50 2015 +0200

```
dm: refactor ioctl handling

This moves the call to blkdev_ioctl and the argument checking to DM core
code, and only leaves a callout to find the block device to operate on
in the targets.  This simplifies the code and allows us to pass through
ioctl-like command using other methods in the next patch.

Also split out a helper around calling the prepare_ioctl method that
will be reused for persistent reservation handling.

Signed-off-by: Christoph Hellwig <hch@lst.de>
Signed-off-by: Mike Snitzer <snitzer@redhat.com>
```

**Comment by Foxcool** [comment]
/var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.c: В функции «flashcache_bio_endio»:
/var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.c:740:2: error: too many arguments for function «bio_endio»
  bio_endio(bio, error);
  ^
In file included from include/linux/blkdev.h:18:0,
                 from /var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.c:29:
include/linux/bio.h:433:13: warning: declared here
 extern void bio_endio(struct bio *);
             ^
scripts/Makefile.build:258: error «/var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.o»

**Comment by akiradeveloper** [comment]
it's due to the API change in 4.3

My driver fixed this problem as
https://github.com/akiradeveloper/dm-writeboost/commit/eec4b59b2b839a3e74406fd9eb60c314c71d18cd


I suppose flash cache can fix this issue too

- Akira

On Sat, Jan 23, 2016 at 7:23 PM, Alexander Babenko <notifications@github.com
> wrote:

> /var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.c: В
> функции «flashcache_bio_endio»:
> /var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.c:740:2:
> error: too many arguments for function «bio_endio»
> bio_endio(bio, error);
> ^
> In file included from include/linux/blkdev.h:18:0,
> from
> /var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.c:29:
> include/linux/bio.h:433:13: warning: declared here
> extern void bio_endio(struct bio *);
> ^
> scripts/Makefile.build:258: error
> «/var/lib/dkms/flashcache/1.0-238-gca7a593606ea/build/flashcache_subr.o»
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/flashcache/issues/215#issuecomment-174168704>
> .
>



-- 
Akira Hayakawa

**Comment by awhitcroft** [comment]
I will note that the fix proposed here fixes the second simpler issue with flashcache against 4.4.  The ioctl issue remains. A quick look at the change in the kernel implies they have removed the ioctl interface for DM devices, only allowing pass through of ioctls to disks underneath.  That appears to preclude adding additional ioctls at the dm level.

**Comment by awhitcroft** [comment]
I did start an upstream conversation on this.  They appear uninterested in this use case: https://lkml.org/lkml/2016/1/28/414

**Comment by awhitcroft** [comment]
Ok, we had some further discussion upstream about how this is "meant" to be done.  It seems there is a target message system for this kind of thing, essentially an existing ioctl which can carry data to and from the target.

I attempted to convert the existing support over to this and have (frankly) bodged the existing user space tooling to use this via a call out to "dmsetup message".  I am sure this is not the final form of the fix, but hope it at least sparks development in the right direction.

I have uploaded flashcache into Ubuntu with this change. I will also proposed a merge-request with this change.

**Comment by awhitcroft** [comment]
Well that did not quite work as expected.  https://github.com/facebook/flashcache/pull/216 is the pull request for the originally reported issue in this bug.  The bio_end part is straight forward.

**Comment by demofly** [comment]
Fixed for my Gentoo 4.4.39 in the next way:

```
git clone https://anonscm.debian.org/git/collab-maint/flashcache.git
cd flashcache
patch -p1 < debian/patches/usable-makefile.patch
patch -p1 < debian/patches/honor-cflags-and-ldflags.patch
patch -p1 < debian/patches/fix-build-error-on-linux-4.3.patch
patch -p1 < debian/patches/switch-from-ioctl-to-dm-target-messages.patch
make install KERNEL_TREE=/usr/src/linux-4.4.39-gentoo/
```
Then, disabled module signing control and rebuilt the kernel.

Works like a charm. 

P.S. The code with patches are cloned from Debian upstream flashcache packages.
